### ISSUE TITLE
Support cancellation by booking ID

### ISSUE THREAD

**Issue by kingjon3377** [utopia-airlines/UtopiaCancellationService#7]
The user should be able to cancel a ticket when in possession of his or her booking ID without having to look up the flight, row, and seat that booking ID corresponds to.

**Comment by al-amine** [comment]
you mean I need to ad another method, service that does the cancellation by the booking Id ?

**Comment by kingjon3377** [comment]
Another controller route, and any service methods needed to implement it. This is needed to implement any of the user-facing APIs, since they have a corresponding route.

**Comment by al-amine** [comment]
okay

**Comment by kingjon3377** [comment]
Fixed in #8.
